Allow distributing the points on the inner surface more smoothly
boutproject/zoidberg pull request #35
Opened 2024-12-09 09:55 UTC by dschwoerer

This commits adds the option `inner_maxmode`, which can be used in combination with `inner_ort` to distribute the points on the inner boundary more smoothly. Unlike `maxmode_inner`, this does not sets a maximum ratio, but ensures that the points are distributed locally smoothly, by removing high frequency modes in the distrbution.

This is not enabled by default, as the value of inner_maxmode depends on the the specific mesh. But it seems that for simple cases, low values around 5 seem to be good.

2025-06-18 19:48 UTC, bendudson commented on zoidberg/field.py
>          m: torodial mode number
This 'm' and 'n' choice seems to be opposite to the usual convention: 'n' is usually used for toroidal mode number, 'm' for poloidal.

2025-06-20 05:14 UTC, bendudson approved these changes

2025-10-07 12:17 UTC, ZedThree requested changes

2025-10-07 13:06 UTC, dschwoerer commented on zoidberg/zoidberg.py
> +        del Z
As long as `R` and `Z` are still in scope, the GC cannot clean them up.
We could also do `R = None` - but i think `del R` is more explicit about the intent.

2025-11-17 15:55 UTC, ZedThree approved these changes

2025-11-17 15:55 UTC, ZedThree commented on zoidberg/zoidberg.py
> +        format="NETCDF4",
Let's just drop this. I'm not sure there are any other sensible choices!

2025-11-24 11:30 UTC, merged